### ISSUE TITLE
NoClassDefFoundError: org/bytedeco/javacpp/Pointer

### ISSUE THREAD

**Issue by nemoo** [kogecoo/dl4j-examples-scala#6]
Hi!

This is more of a usage question than a bug report: 

When I try to run the examples I get this error (after it compiles successfully):
`[error] (run-main-0) java.lang.NoClassDefFoundError: org/bytedeco/javacpp/Pointer
java.lang.NoClassDefFoundError: org/bytedeco/javacpp/Pointer
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
`

Did I miss something in the setup? I just compiled everything and then ran it (on Windows 10 / 64bit). 

Thanks!

**Comment by kogecoo** [comment]
Thanks for your reporting, and  I'm sorry for the inconvenience.

The problem reproduces my environment  (so that is my fault), and I fixed it.

Now that you will be able to build this project, but notice that it requires some modification of `build.sbt` depends on your  OS environment because of Nd4j restriction.
You can find the instruction at "Before building this project " section of `README.md`.

**Comment by nemoo** [comment]
Works perfectly now. Thanks for the quick fix!
